// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-bbs/app/dao/internal"
)

// topicsDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type topicsDao struct {
	*internal.TopicsDao
}

var (
	// Topics is globally public accessible object for table topics operations.
	Topics = topicsDao{
		internal.NewTopicsDao(),
	}
)

// Fill with you ideas below.
